
# Ignore White Space for Prototype

# Declare Type
Type;

# Lambda Types

# A type term
Identifier = printable_utf8, (*printable_utf8)

TypeList = '[', Type, *(',', Type), ']'

LocalityType = 'Local', 'Global', 'Safe', 'Stack'

# Lambda type with a capture list
LambdaType = 'Lam', LocalityType, TypeList, ArrowType

# Arrow types Domain to Codomain
ArrowType = Type, '->', Type 

# Type FunApp, this is how we support kinds.
TypeApp = Identifier, ws, Type 

# Define Type
Type = LambdaType | ArrowType | TypeApp | Identifier 

# Statements 
Kind = '*', *('->', Kind)
DataStmt = 'data', Identifier, Kind, '{', ConstructorList, '}'
Constructor = Identifier, ':', Type 
ConstructorList = Constructor, *(',', Constructor)

# Type Judgement (Forward Declarations/Header File)
TypeDef = Identifier, ':', Type, ';'

# Declar Expr 
Expr;

# Lambda Functions
Locality = 'global' | 'local' | 'safe' | 'stack'
CaptureList = '[', Identifier, *(',', ArgList), ']'
ArgList = '(', Identifier, *(',', ArgList), ')'
Lambda = 'lam', Locality, CaptureList, ArgList, '.', Expr 

# Function FunApp 
FunApp = Expr, ws, Expr 

WhileStmt = 'while', '(', Expr, ')', Expr 
DoWhileStmt = 'do', Expr, 'while', '(', Expr, ')'
ForStmt = 'for', '(', Stmt, ';', Expr, ';', Stmt, ')', Expr 

Pattern = Identifier, *(',', Identifier)
Case = Pattern, '->', Expr
CaseList = '{', Case, *(';', Case), '}'
MatchStmt = 'match', '(', Expr, ')', CaseList 

# DefStmt 
DefStmt = Identifier, '=', Expr, ';'

# Assignment 
AssignRef = # tbd 
AssignStmt = AssignRef, '<-', Expr  

# Return 
ReturnStmt = 'return', Expr 

# Block 
BlockStmt = AssignStmt | DefStmt | ReturnStmt | WhileStmt | DoWhileStmt | ForStmt | MatchStmt 
BlockStmtList = BlockStmt, *(';', BlockStmt)
Block = '{', BlockStmtList, '}'

# Statement Forward Decl
Stmt = AssignStmt | DefStmt | DataStmt | TypeDef

Paren = '(', Expr, ')'

Term = Identifier | Number | String | Paren

Expr = Block | MatchStmt | Lambda | FunApp | Term 


